/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WeaponService } from "../weapon.service";
import { WeaponCreateInput } from "./WeaponCreateInput";
import { Weapon } from "./Weapon";
import { WeaponFindManyArgs } from "./WeaponFindManyArgs";
import { WeaponWhereUniqueInput } from "./WeaponWhereUniqueInput";
import { WeaponUpdateInput } from "./WeaponUpdateInput";
import { SkinFindManyArgs } from "../../skin/base/SkinFindManyArgs";
import { Skin } from "../../skin/base/Skin";
import { SkinWhereUniqueInput } from "../../skin/base/SkinWhereUniqueInput";

export class WeaponControllerBase {
  constructor(protected readonly service: WeaponService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Weapon })
  async createWeapon(@common.Body() data: WeaponCreateInput): Promise<Weapon> {
    return await this.service.createWeapon({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        typeField: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Weapon] })
  @ApiNestedQuery(WeaponFindManyArgs)
  async weapons(@common.Req() request: Request): Promise<Weapon[]> {
    const args = plainToClass(WeaponFindManyArgs, request.query);
    return this.service.weapons({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        typeField: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Weapon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async weapon(
    @common.Param() params: WeaponWhereUniqueInput
  ): Promise<Weapon | null> {
    const result = await this.service.weapon({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        typeField: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Weapon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWeapon(
    @common.Param() params: WeaponWhereUniqueInput,
    @common.Body() data: WeaponUpdateInput
  ): Promise<Weapon | null> {
    try {
      return await this.service.updateWeapon({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Weapon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWeapon(
    @common.Param() params: WeaponWhereUniqueInput
  ): Promise<Weapon | null> {
    try {
      return await this.service.deleteWeapon({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/skins")
  @ApiNestedQuery(SkinFindManyArgs)
  async findSkins(
    @common.Req() request: Request,
    @common.Param() params: WeaponWhereUniqueInput
  ): Promise<Skin[]> {
    const query = plainToClass(SkinFindManyArgs, request.query);
    const results = await this.service.findSkins(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,

        weapon: {
          select: {
            id: true,
          },
        },

        pattern: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/skins")
  async connectSkins(
    @common.Param() params: WeaponWhereUniqueInput,
    @common.Body() body: SkinWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skins: {
        connect: body,
      },
    };
    await this.service.updateWeapon({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/skins")
  async updateSkins(
    @common.Param() params: WeaponWhereUniqueInput,
    @common.Body() body: SkinWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skins: {
        set: body,
      },
    };
    await this.service.updateWeapon({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/skins")
  async disconnectSkins(
    @common.Param() params: WeaponWhereUniqueInput,
    @common.Body() body: SkinWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skins: {
        disconnect: body,
      },
    };
    await this.service.updateWeapon({
      where: params,
      data,
      select: { id: true },
    });
  }
}
